services:
  postgres:
    image: postgres:15
    container_name: postgres_gestor
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gestor_horarios
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gestor_horarios"]
      interval: 10s
      timeout: 5s
      retries: 5

 
volumes:
  postgres_data: