// features/asignaciones/index.ts

export * from "./types"
export { asignacionesService }     from "./services/asignacionesService"
export { useAsignaciones }         from "./hooks/useAsignaciones"
export { useAsignacionDetalle }    from "./hooks/useAsignacionDetalle"
export type { AsignacionDetalle }  from "./hooks/useAsignacionDetalle"
export { useEditarAsignacion }     from "./hooks/useEditarAsignacion"
export type { EditarFormData }     from "./hooks/useEditarAsignacion"
export { ModalConfirmar }          from "./components/ModalConfirmar"
export { AsignacionFilters }       from "./components/AsignacionFilters"
export { CambiarTitularForm }      from "./components/CambiarTitularForm"
export { AsignacionForm }          from "./components/AsignacionForm"
export { AsignacionesTable }       from "./components/AsignacionesTable"
export { AsignacionDetalleHeader } from "./components/AsignacionDetalleHeader"
export { TitularCard }             from "./components/TitularCard"
export { CargoCard }               from "./components/CargoCard"
export { DistribucionesCard }      from "./components/DistribucionesCard"
export { IncidenciasCard }         from "./components/IncidenciasCard"
export { EditarAsignacionForm }    from "./components/EditarAsignacionForm"