// features/distribuciones/index.ts
export * from "./types"
export { distribucionesService }        from "./services/distribucionesService"
export { useDistribuciones }            from "./hooks/useDistribuciones"
export { DistribucionList }             from "./components/DistribucionList"
export { DistribucionRow }              from "./components/DistribucionRow"
export { DistribucionForm }             from "./components/DistribucionForm"
export { DistribucionFilters }          from "./components/DistribucionFilters"
export { SinDistribucionBadges }        from "./components/SinDistribucionBadges"
export { SinModulosBadges }             from "./components/SinModulosBadges"
export { ModalEliminarConReemplazo }    from "./components/ModalEliminarConReemplazo"